### ISSUE TITLE
API issues

### ISSUE THREAD

**Issue by FahaxikiHoney** [Future-House/paper-qa#460]
from paperqa import Settings, ask
import os
os.environ["OPENAI_API_KEY"] = "EMPTY"
local_llm_config = {
    "model_list": [
        {
            "model_name": "ollama/llama3",
            "litellm_params": {
                "model": "ollama/llama3",
                "api_base": 
            }
        }
    ]
}

answer = ask(
    "What manufacturing challenges are unique to bispecific antibodies?",
    settings=Settings(
        llm="ollama/llama3",
        llm_config=local_llm_config,
        summary_llm="ollama/llama3",
        summary_llm_config=local_llm_config,
    ),
)

When I run the above code, I get an error. The error is as follows

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "D:\Study\论文\检索增强\paper-qa-main\1.py", line 16, in <module>
    answer = ask(
             ^^^^
  File "D:\Study\论文\检索增强\paper-qa-main\paperqa\agents\__init__.py", line 92, in ask
    return get_loop().run_until_complete(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\asyncio\base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "D:\Anaconda\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "D:\Anaconda\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "D:\Anaconda\Lib\asyncio\base_events.py", line 1948, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\asyncio\windows_events.py", line 445, in select
    self._poll(timeout)
  File "D:\Anaconda\Lib\asyncio\windows_events.py", line 774, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

**Comment by jamesbraza** [comment]
Based on your error, it looks like you hit CTRL-C (per the `KeyboardInterrupt`) during the run

**Comment by qingqiyangqidanqi** [comment]
> import os
> os.environ["OPENAI_API_KEY"] = "EMPTY"

Hello, may I ask if this is to solve openai_ error?

**Comment by maykcaldas** [comment]
Hello @FahaxikiHoney, could you solve your issue?

I will close the issue due to its inactivity. However, you can reopen it if you need to follow up.
