### ISSUE TITLE
EmptyDocsError: Not gathering evidence due to having no papers.

### ISSUE THREAD

**Issue by SURUIYUAN** [Future-House/paper-qa#470]
Why show ”EmptyDocsError: Not gathering evidence due to having no papers.“ It can not detect my paper?

**Comment by SURUIYUAN** [comment]
How to modify in python program, explain in detail.

**Comment by SURUIYUAN** [comment]
How to modify in python program, explain in detail.

**Comment by wight911** [comment]
HI there, I hit the same problems as yours. Did you solved that 'Not gathering evidence due to having no papers' problem by following Dosu's suggestions? Could you please let us know where the key is.
thanks.

**Comment by wight911** [comment]
I attached my output info as follows. There is a pdf file in my_papers/ there. I can use openai api very correctly. 
when I changed the model to ollama/llama3.2, it seems not working properly.

I put some print(...) code inside 'async def paper_search(...)', but fail to see that. It seems the paper_search() is never called.



OUTPUT INFO: 
------

(paperqa) D:\git-base\paper-qa\my_papers>pqa --settings my_local_settings ask "what is PENS dataset?"
C:\Users\wight\anaconda3\envs\paperqa\Lib\site-packages\pydantic\_internal\_config.py:345: UserWarning: Valid config keys have changed in V2:
* 'fields' has been removed
  warnings.warn(message, UserWarning)
entering main ---------
cli_settings: CliSettingsSource(env_nested_delimiter='.', env_prefix_len=0)
args: Namespace(settings='my_local_settings', index='default', command='ask', query='what is PENS dataset?')
remaining_args: []
Could not find cost for model ollama/llama3.2.
Encountered exception during tool call for tool gather_evidence: EmptyDocsError('Not gathering evidence due to having no papers.')
[12:32:16] Trajectory failed.
           ╭──────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────╮           │ C:\Users\wight\anaconda3\envs\paperqa\Lib\site-packages\litellm\main.py:463 in acompletion                 │           │                                                                                                            │           │    460 │   │   │   │   response = ModelResponse(**init_response)                                           │           │    461 │   │   │   response = init_response                                                                │           │    462 │   │   elif asyncio.iscoroutine(init_response):                                                    │           │ ❱  463 │   │   │   response = await init_response                                                          │           │    464 │   │   else:                                                                                       │



.......(truincated for brevity) ......




     │   265 │   │   │   │   │   │   },                                                                           │           │   266 │   │   │   │   │   │   "type": "function",                                                          │           ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯           
KeyError: 'name'

During handling of the above exception, another exception occurred:

           ╭──────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────╮           │ C:\Users\wight\anaconda3\envs\paperqa\Lib\site-packages\paperqa\agents\main.py:157 in                      │           │ _run_with_timeout_failure                                                                                  │           │                                                                                                            │           │   154 ) -> tuple[PQASession, AgentStatus]:                                                                 │           │   155 │   try:                                                                                             │           │   156 │   │   async with asyncio.timeout(settings.agent.timeout):                                          │



.......(truincated for brevity) ......


  │   2169 │   │   │   │   │   ),                                                                              │           ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯          
 APIConnectionError: litellm.APIConnectionError: 'name'
           Traceback (most recent call last):
             File "C:\Users\wight\anaconda3\envs\paperqa\Lib\site-packages\litellm\main.py", line 463, in acompletion
               response = await init_response
                          ^^^^^^^^^^^^^^^^^^^
             File
           "C:\Users\wight\anaconda3\envs\paperqa\Lib\site-packages\litellm\llms\custom_httpx\llm_http_handler.py", line
           177, in async_completion
               return provider_config.transform_response(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             File
           "C:\Users\wight\anaconda3\envs\paperqa\Lib\site-packages\litellm\llms\ollama\completion\transformation.py",
           line 263, in transform_response
               "name": function_call["name"],
                       ~~~~~~~~~~~~~^^^^^^^^
           KeyError: 'name'

           Received Model Group=ollama/llama3.2
           Available Model Group Fallbacks=None LiteLLM Retried: 2 times, LiteLLM Max Retries: 3
[12:32:24] Generating answer for 'what is PENS dataset?'.
Could not find cost for model ollama/llama3.2.
[12:35:38] Status: Paper Count=0 | Relevant Papers=0 | Current Evidence=0 | Current Cost=$0.0000
           Answer: I cannot provide information about the PENS dataset as it is not a widely recognized or
           well-documented dataset. Can I help you with something else?

(paperqa) D:\git-base\paper-qa\my_papers>

**Comment by maykcaldas** [comment]
Hello @SURUIYUAN and @wight911,

@SURUIYUAN , do you mind sharing a minimal code to reproduce the problem? It is possible that your `settings.agent.index.paper_directory` points to the wrong directory?
Please check [this tutorial](https://futurehouse.gitbook.io/futurehouse-cookbook/paperqa/docs/tutorials/settings_tutorial) where we show a little on how to work with the `Settings` class.

@wight911 It seems that the cli worked well with OpenAI's models, is that correct? We know that `ollama/llama3.2` fails in follow the required schema sometimes and it leads to some errors. Please check [this discussion](https://github.com/Future-House/paper-qa/discussions/753)

**Comment by jamesbraza** [comment]
Hi all to circle back on a few things here:

> Could not find cost for model ollama/llama3.2.

This is a `litellm` missing cost entry: https://github.com/BerriAI/litellm/issues/9644

> APIConnectionError: litellm.APIConnectionError: 'name' Traceback (most recent call last): File "C:\Users\wight\anaconda3\envs\paperqa\Lib\site-packages\litellm\main.py", line 463, in acompletion response = await init_response ^^^^^^^^^^^^^^^^^^^ File "C:\Users\wight\anaconda3\envs\paperqa\Lib\site-packages\litellm\llms\custom_httpx\llm_http_handler.py", line 177, in async_completion return provider_config.transform_response( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\wight\anaconda3\envs\paperqa\Lib\site-packages\litellm\llms\ollama\completion\transformation.py", line 263, in transform_response "name": function_call["name"], ~~~~~~~~~~~~~^^^^^^^^ KeyError: 'name'

This is a `litellm` bug: https://github.com/BerriAI/litellm/issues/8594

Hopefully they get fixed, but these are not `paper-qa` issues, they're issues in our upstream
