### ISSUE TITLE
Low relevance for Doc().query answer

### ISSUE THREAD

**Issue by Snikch63200** [Future-House/paper-qa#557]
Hello,

I wonder why my Doc().query request often achieve random and often poor quality answers i term of relevance.

Papers are sometimes relevant sometimes not... Citations are, most of time, completly off-topic even if selected document contains relevant informations. 

I use this config for LiteLLM model : 

```
 local_llm_config = dict(
    model_list=[
        dict(
            model_name=f"openai/my-llm-model",
            litellm_params=dict(
                model=f"openai/my-llm-model",
                api_base="http://192.168.1.15:8080/v1/",
                api_key="sk-no-key-required",
                verbose=3,
                temperature=0.1,
                frequency_penalty=1.5,
                max_tokens=2048,
            ),
        )
    ]
)
```
With these answer parameters : 

```
settings.answer.answer_max_sources = 4
settings.answer.evidence_k = 10
settings.answer.evidence_retrieval = True
```

I use a SparseEmbedding model as follows to run a full local PaperQA instance : 

`embedding_model = SparseEmbeddingModel(ndim=4096)`

Is it a parameter problem (like number of tokens) or an embedding model problem (I read in code documentation sparse embedding is a very simple approach).

Best regards. @Dosu.

**Comment by Snikch63200** [comment]
How can I define a LiteLLM embedding model for a local embedding model ? @Dosu.

**Comment by Snikch63200** [comment]
I defined my local embedding model as follows : 

    ```
embedding_model = HybridEmbeddingModel([LiteLLMEmbeddingModel.from_name(f"openai/my-llm-model"),
                                            SparseEmbeddingModel(ndim=4096)])
```

Got this error : 

```
Traceback (most recent call last):
  File "C:\Users\XXXXXXXXXXX\Desktop\PaperQA\paper_qa_question_async.py", line 85, in <module>
    asyncio.run(my_query())
  File "C:\ProgramData\anaconda3\envs\PaperQA_env\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\PaperQA_env\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\PaperQA_env\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\XXXXXXXXXXX\Desktop\PaperQA\paper_qa_question_async.py", line 66, in my_query
    embedding_model = HybridEmbeddingModel([LiteLLMEmbeddingModel.from_name(f"openai/my-llm-model"),
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\PaperQA_env\Lib\site-packages\pydantic\_internal\_model_construction.py", line 262, in __getattr__
    raise AttributeError(item)
AttributeError: from_name. Did you mean: 'from_orm'?
```

Any solution ? @Dosa.
