### ISSUE TITLE
save and import embeddings for faster answer generation

### ISSUE THREAD

**Issue by n400peanuts** [Future-House/paper-qa#721]
Hello,

Thank you for the fantastic work on PaperQA. I’ve been able to use it to ask questions by providing over 100 papers as input, and I’ve been using only local models via Ollama. Everything is working well, but I’d like to know how I can avoid reloading the same files and retraining an embedding model each time I have a new Question.

Is there a way to save the vector store and load it later, so it can be used by the LLM to generate answers? I couldn't find documentation about that, I found something re- caching, but it's unclear to me how to use it properly. Can you provide some help?

best wishes

My code so far:

```python
from paperqa import Settings, ask

question = "Can you list all climate-sensitive pathways that affect rotavirus incidence?"



model = "ollama/llama3.1" # "ollama/llama3.2" 
embedding = "ollama/nomic-embed-text" # "nomic-embed-text"

local_llm_config = {
    "model_list": [
        {
            "model_name": model,
            "litellm_params": {
                "model": model,
                "api_base": "http://localhost:11434",
            },
            "answer": {
                "evidence_k": 40,
                "evidence_detailed_citations": True,
                "evidence_summary_length": "about 100 words",
                "answer_max_sources": 5,
                "answer_length": "about 300 words, but can be longer",
                "max_concurrent_requests": 4,
                "answer_filter_extra_background": False
            }
            
        }
    ]
}

answer = ask(
    question,
    settings=Settings(
        llm=model,
        llm_config=local_llm_config,
        summary_llm=model,
        summary_llm_config=local_llm_config,
        agent=AgentSettings(
            agent_llm=model, agent_llm_config=local_llm_config
        ),
        embedding=embedding,
        paper_directory="papers/"
    ),
)
```

**Comment by n400peanuts** [comment]
ok let's do a step back. Show me:

1. How to add my documents to the Docs object and how this is used in to generate the embeddings

2. Show me how to use the loaded embeddings in the code to generate the answer

**Comment by n400peanuts** [comment]
Show me how to set to use the following embedding model when generating the embeddings stored into Docs

`embedding = "ollama/nomic-embed-text" # "nomic-embed-text"`

**Comment by rahmanmus** [comment]
@n400peanuts Have you figured this out? I'm in same boat, using llama3.2 and mxbai embdedding to pickle the docs, but can't load them. I get openai authentication error. Any help would be greatly appreciated.

**Comment by rahmanmus** [comment]
When I try that, I get this error:

`/home/rahman/.pyenv/versions/py312paperqa/lib/python3.12/site-packages/pydantic/_internal/_config.py:345: UserWarning: Valid config keys have changed in V2:
* 'fields' has been removed
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/home/rahman/Documents/plasma-RAG/sandbox.py", line 76, in <module>
    session = docs.query(
              ^^^^^^^^^^^
  File "/home/rahman/.pyenv/versions/py312paperqa/lib/python3.12/site-packages/paperqa/docs.py", line 674, in query
    return get_loop().run_until_complete(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rahman/.pyenv/versions/3.12.7/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/rahman/.pyenv/versions/py312paperqa/lib/python3.12/site-packages/paperqa/docs.py", line 716, in aquery
    session = await self.aget_evidence(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rahman/.pyenv/versions/py312paperqa/lib/python3.12/site-packages/paperqa/docs.py", line 605, in aget_evidence
    matches = await self.retrieve_texts(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rahman/.pyenv/versions/py312paperqa/lib/python3.12/site-packages/paperqa/docs.py", line 532, in retrieve_texts
    await self.texts_index.max_marginal_relevance_search(
  File "/home/rahman/.pyenv/versions/py312paperqa/lib/python3.12/site-packages/paperqa/llms.py", line 143, in max_marginal_relevance_search
    texts, scores = await self.similarity_search(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rahman/.pyenv/versions/py312paperqa/lib/python3.12/site-packages/paperqa/llms.py", line 256, in similarity_search
    embedding_model.set_mode(EmbeddingModes.QUERY)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'set_mode'`

**Comment by n400peanuts** [comment]
Hi @rahmanmus if you get weird openai authentication errors in my case it meant that somewhere there was a variable which called a model and the default was calling openai. Dig into the `settings.py` to see where/when the package calls which llm and set all variables to call your local llm/embeddings model. This should solve the issue.

**Comment by n400peanuts** [comment]
@rahmanmus yay! happy that it helped!
