### ISSUE TITLE
'NumpyVectorStore' object has no attribute '_texts_filter'

### ISSUE THREAD

**Issue by DGoettlich** [Future-House/paper-qa#779]
Hi,

 trying to query my vector database with paper-qa@5.8.0, im getting

Traceback (most recent call last):
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rag-8oWIogsS-py3.12/lib/python3.12/site-packages/pydantic/main.py", line 871, in __getattr__
    return self.__pydantic_private__[item]  # type: ignore
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: '_texts_filter'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  [...]
    answer = docs.query(question, 
             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rag-8oWIogsS-py3.12/lib/python3.12/site-packages/paperqa/docs.py", line 680, in query
    return get_loop().run_until_complete(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rag-8oWIogsS-py3.12/lib/python3.12/site-packages/paperqa/docs.py", line 722, in aquery
    session = await self.aget_evidence(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rag-8oWIogsS-py3.12/lib/python3.12/site-packages/paperqa/docs.py", line 611, in aget_evidence
    matches = await self.retrieve_texts(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rag-8oWIogsS-py3.12/lib/python3.12/site-packages/paperqa/docs.py", line 537, in retrieve_texts
    await self.texts_index.max_marginal_relevance_search(
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rag-8oWIogsS-py3.12/lib/python3.12/site-packages/paperqa/llms.py", line 856, in max_marginal_relevance_search
    texts, scores = await self.similarity_search(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rag-8oWIogsS-py3.12/lib/python3.12/site-packages/paperqa/llms.py", line 977, in similarity_search
    if self._texts_filter is not None:
       ^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/Library/Caches/pypoetry/virtualenvs/rag-8oWIogsS-py3.12/lib/python3.12/site-packages/pydantic/main.py", line 873, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
AttributeError: 'NumpyVectorStore' object has no attribute '_texts_filter'

the problem does not seem to exist when i downgrade to paper-qa=5.0.5. Any idea what I might be doing wrong on 5.8.0?

Thanks in advance!

**Comment by jamesbraza** [comment]
Hi @DGoettlich interesting bug. Can you share what version of Pydantic you are using, and can you figure out exactly the highest version of PaperQA that doesn't hit this issue for you? For example, I think v5.0.6 should work fine too.

**Comment by DGoettlich** [comment]
Hi @jamesbraza thanks for the quick reply! 

I was using pydantic 2.10.4 but trying to find out which was the highest version of PaperQA that doesnt hit the issue, I couldn't replicate the error from yesterday. Guess that closes the issue – sorry and thanks for the quick help!
