### ISSUE TITLE
AIOHTTP Error

### ISSUE THREAD

**Issue by VSandwar74** [Future-House/paper-qa#781]
```bash
$pqa --llm groq/llama3-8b-8192 --summary_llm groq/llama3-8b-8192 ask "what is ARCH"                                            
```
```
  + Exception Group Traceback (most recent call last):
  |   File "/Library/Frameworks/Python.framework/Versions/3.11/bin/pqa", line 8, in <module>
  |     sys.exit(main())
  |              ^^^^^^
...
    |   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/__init__.py", line 254, in __getattr__
    |     raise AttributeError(f"module {__name__} has no attribute {name}")
    | AttributeError: module aiohttp has no attribute ClientConnectionResetError. Did you mean: 'ClientConnectionError'?
    +------------------------------------
sys:1: RuntimeWarning: coroutine 'MetadataPostProcessor.process' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x12a121c50>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x12ca95e80>, 25720.358243708)]']
connector: <aiohttp.connector.TCPConnector object at 0x1296000d0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x12cad2850>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x12ca96190>, 25719.605680375)]']
connector: <aiohttp.connector.TCPConnector object at 0x12cd0e8d0>
```

I've tried solving this error for so long, I've previously had some issues with SSL certificates, but those _should_ be resolved by now.  Issue at https://github.com/Future-House/paper-qa/issues/759, should solve the problem but I've used both aiohttp==3.10.6
and aiohttp==3.11.11, both to same problem. Running this on a .venv/bin/python, 3.11, macOS, certifi==2024.12.14, paper-qa==5.8.0. I've exported my GROQ api-key. I've also ran this on a main.py, to no avail.

```python
from paperqa import Settings, ask, Docs
from dotenv import load_dotenv
load_dotenv()

answer = ask(
    "What manufacturing challenges are unique to bispecific antibodies?",
    settings=Settings(
        llm="groq/llama3-8b-8192", 
        summary_llm="groq/llama3-8b-8192",
        paper_directory="docs",
    ),
)
```

**Comment by VSandwar74** [comment]
├── litellm [required: >=1.44, installed: 1.56.4]
│   ├── aiohttp [required: Any, installed: 3.10.6]
│   │   ├── aiohappyeyeballs [required: >=2.3.0, installed: 2.4.4]
│   │   ├── aiosignal [required: >=1.1.2, installed: 1.3.2]
│   │   │   └── frozenlist [required: >=1.1.0, installed: 1.5.0]
│   │   ├── attrs [required: >=17.3.0, installed: 24.3.0]
│   │   ├── frozenlist [required: >=1.1.1, installed: 1.5.0]
│   │   ├── multidict [required: >=4.5,<7.0, installed: 6.1.0]
│   │   └── yarl [required: >=1.12.0,<2.0, installed: 1.18.3]
│   │       ├── idna [required: >=2.0, installed: 3.10]
│   │       ├── multidict [required: >=4.0, installed: 6.1.0]
│   │       └── propcache [required: >=0.2.0, installed: 0.2.1]

**Comment by jamesbraza** [comment]
Hi @VSandwar74 looks like you are hitting: `AttributeError: module aiohttp has no attribute ClientConnectionResetError. Did you mean: 'ClientConnectionError'?`

To share, we use `aiohttp==3.11.10` in our local dev right now: https://github.com/Future-House/paper-qa/blob/525bb320e962df7ddff514acb07977999a8d3677/uv.lock#L31-L32

I am thinking you might have a different `aiohttp` version in your actual env than what is printed by `pip list`.

When you run your Python module, can you `print` the `aiohttp.__version__` to confirm what version you have?

```python
import aiohttp
from paperqa import Settings, ask, Docs
from dotenv import load_dotenv

print(aiohttp.__version__)

load_dotenv()

answer = ask(
    ...
)
```
