### ISSUE TITLE
ValueError("Number of columns in X and Y must be the same.")

### ISSUE THREAD

**Issue by clecarosc** [Future-House/paper-qa#79]
Hi!
Testing with the usage instructions 

```python
import paperqa
from paperqa import Docs
import glob

my_docs = glob.glob("./shimizu/*.pdf")

docs = Docs()
for d in my_docs:
    docs.add(d)
    
answer = docs.query("Does papilloma virus cause digital Bowen disease?", k = 5, max_sources = 2)
print(answer.formatted_answer)
``` 

I am having the following error: **ValueError: Number of columns in X and Y must be the same**
In terminal I got this:

```shell
Traceback (most recent call last):
  File "/Users/clec/paper-qa/tests/test.py", line 11, in <module>
    answer = docs.query("Does papilloma virus cause digital Bowen disease?", k = 5, max_sources = 2)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/paperqa/docs.py", line 374, in query
    return loop.run_until_complete(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/paperqa/docs.py", line 406, in aquery
    answer = await self.aget_evidence(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/paperqa/docs.py", line 282, in aget_evidence
    docs = self._faiss_index.max_marginal_relevance_search(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/vectorstores/faiss.py", line 285, in max_marginal_relevance_search
    docs = self.max_marginal_relevance_search_by_vector(embedding, k, fetch_k)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/vectorstores/faiss.py", line 248, in max_marginal_relevance_search_by_vector
    mmr_selected = maximal_marginal_relevance(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/vectorstores/utils.py", line 19, in maximal_marginal_relevance
    similarity_to_query = cosine_similarity([query_embedding], embedding_list)[0]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/math_utils.py", line 16, in cosine_similarity
    raise ValueError("Number of columns in X and Y must be the same.")
ValueError: Number of columns in X and Y must be the same.
``` 

I've noticed that a similar [issue](https://github.com/hwchase17/langchain/issues/3384) is raised in langchain repo (it could be a problem using FAISS index as vector store ?). 
I'm using ` langchain==0.0.147`

Thanks!

**Comment by catbears** [comment]
Similar issue here. I ran into an issue `Failed to tokenize` in a 700 word text file, then I used a 5 word text file and got the X Y thing. The key is there, because there is another error which recommends this :)


```python
# See the readme in the repo
# https://github.com/whitead/paper-qa

# We go for locally hosted of course
from langchain.embeddings import LlamaCppEmbeddings
from langchain.llms import LlamaCpp
from paperqa import Docs

llm = LlamaCpp(model_path="ggml-model-q4_0.bin")
embeddings = LlamaCppEmbeddings(model_path="ggml-model-q4_0.bin")

docs = Docs(llm=llm, embeddings=embeddings)

# pdfs/merger.txt is a 'big' document, mini.txt contains one sentence
docs.add(path="pdfs/mini.txt",
         citation="thomas_birthday",
         disable_check=True,
         key='mykey')

answer = docs.query("What does the birthday cake do?")
print(answer.formatted_answer)
```

Running the example is fine:
```python
from langchain.embeddings import LlamaCppEmbeddings

llama = LlamaCppEmbeddings(model_path="ggml-model-q4_0.bin")

with open('pdfs/mini.txt', 'r') as file:
    text = file.read().replace('\n', ' ')

query_result = llama.embed_query(text)

doc_result = llama.embed_documents([text])
```

**Comment by whitead** [comment]
Should be fixed in latest langchain release
